"""m3_protocols_artifacts_escalation

Revision ID: 005
Revises: 004
Create Date: 2026-05-04 23:45:10.764369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_chains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation_chains', schema=None) as batch_op:
        batch_op.create_index('idx_ec_project', ['project_id'], unique=False)

    op.create_table('protocols',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), server_default='1.0', nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('escalation_chain', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('loaded_from', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.create_index('idx_protocols_active', ['project_id', 'is_active'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_agent', sa.Uuid(), nullable=True),
    sa.Column('created_by_user', sa.Uuid(), nullable=True),
    sa.Column('linked_task_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_breaking', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('idx_artifacts_project', ['project_id'], unique=False)
        batch_op.create_index('idx_artifacts_project_type', ['project_id', 'artifact_type'], unique=False)
        batch_op.create_index('idx_artifacts_status', ['project_id', 'status'], unique=False)

    op.create_table('protocol_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('linked_task_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('actor_assignments', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('escalation_step', sa.Integer(), nullable=True),
    sa.Column('triggering_event_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_transitioned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_instances', schema=None) as batch_op:
        batch_op.create_index('idx_pi_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('idx_pi_protocol', ['protocol_id'], unique=False)

    op.create_table('artifact_watchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('watcher_kind', sa.String(), nullable=False),
    sa.Column('watcher_id', sa.Uuid(), nullable=False),
    sa.Column('event_filter', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_watchers', schema=None) as batch_op:
        batch_op.create_index('idx_aw_artifact', ['artifact_id'], unique=False)
        batch_op.create_index('idx_aw_watcher', ['watcher_kind', 'watcher_id'], unique=False)

    op.create_table('protocol_timeouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_instance_id', sa.Uuid(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('timeout_action', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_instance_id'], ['protocol_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_timeouts', schema=None) as batch_op:
        batch_op.create_index('idx_pto_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_pto_instance', ['protocol_instance_id'], unique=False)

    op.create_table('protocol_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_instance_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.String(), server_default='', nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=True),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=False),
    sa.Column('guard_context', sa.JSON(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_instance_id'], ['protocol_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_transitions', schema=None) as batch_op:
        batch_op.create_index('idx_pt_instance', ['protocol_instance_id'], unique=False)
        batch_op.create_index('idx_pt_instance_ts', ['protocol_instance_id', 'transitioned_at'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('origin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('protocol_transitions', schema=None) as batch_op:
        batch_op.drop_index('idx_pt_instance_ts')
        batch_op.drop_index('idx_pt_instance')

    op.drop_table('protocol_transitions')
    with op.batch_alter_table('protocol_timeouts', schema=None) as batch_op:
        batch_op.drop_index('idx_pto_instance')
        batch_op.drop_index('idx_pto_expires')

    op.drop_table('protocol_timeouts')
    with op.batch_alter_table('artifact_watchers', schema=None) as batch_op:
        batch_op.drop_index('idx_aw_watcher')
        batch_op.drop_index('idx_aw_artifact')

    op.drop_table('artifact_watchers')
    with op.batch_alter_table('protocol_instances', schema=None) as batch_op:
        batch_op.drop_index('idx_pi_protocol')
        batch_op.drop_index('idx_pi_project_status')

    op.drop_table('protocol_instances')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('idx_artifacts_status')
        batch_op.drop_index('idx_artifacts_project_type')
        batch_op.drop_index('idx_artifacts_project')

    op.drop_table('artifacts')
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_index('idx_protocols_active')

    op.drop_table('protocols')
    with op.batch_alter_table('escalation_chains', schema=None) as batch_op:
        batch_op.drop_index('idx_ec_project')

    op.drop_table('escalation_chains')
    # ### end Alembic commands ###
